attributes:
  action: /forms/base
  method: POST
fields:
  - name: checkbox_field
    type: checkbox
    options:
      label: Checkbox Fields
      boxes:
        hodor: Hodor
        jon: John Snow
        lorem: Ipsum
    constraints:
      Choice:
        choices:
          - hodor
          - jon
        multiple: true
        multipleMessage: Pick only GOT characters
        min: 1
  - name: field1
    type: text
    options:
      label: Text Field
    constraints:
      - NotBlank
  - name: field2
    type: radio
    options:
      label: Here is a Radio
      radios:
        hodor: Hodor
        jon: John Snow
    constraints:
      - NotBlank
  - name: field3
    type: textarea
    options:
      label: Textarea
    constraints:
      NotBlank: []
      Length:
        min: 10
        max: 140
